### ISSUE TITLE
Crash when mining Uranium

### ISSUE THREAD

**Issue by drakray** [grim3212/grim-pack#10]
Got this thing on my server after being kicked
http://pastebin.com/PmFavizS

Server was still running, but I couldn't get back on it

I restarted my server and client, server got running well, client still can't connect, with this
`java.lang.NullPointerException
    at mezz.jei.util.StackHelper.getSubtypes(StackHelper.java:215) [StackHelper.class:?]
    at mezz.jei.plugins.vanilla.furnace.SmeltingRecipeMaker.getFurnaceRecipes(SmeltingRecipeMaker.java:28) [SmeltingRecipeMaker.class:?]
    at mezz.jei.plugins.vanilla.VanillaPlugin.register(VanillaPlugin.java:100) [VanillaPlugin.class:?]
    at mezz.jei.ProxyCommonClient.startJEI(ProxyCommonClient.java:169) [ProxyCommonClient.class:?]
    at mezz.jei.ProxyCommonClient.onEntityJoinedWorld(ProxyCommonClient.java:142) [ProxyCommonClient.class:?]
    at net.minecraftforge.fml.common.eventhandler.ASMEventHandler_418_ProxyCommonClient_onEntityJoinedWorld_EntityJoinWorldEvent.invoke(.dynamic) [?:?]
    at net.minecraftforge.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:72) [ASMEventHandler.class:?]
    at net.minecraftforge.fml.common.eventhandler.EventBus.post(EventBus.java:168) [EventBus.class:?]
    at net.minecraft.world.World.func_72838_d(World.java:1127) [aid.class:?]
    at net.minecraft.client.multiplayer.WorldClient.func_72838_d(WorldClient.java:195) [bln.class:?]
    at net.minecraft.client.Minecraft.func_71353_a(Minecraft.java:2451) [bcx.class:?]
    at net.minecraft.client.Minecraft.func_71403_a(Minecraft.java:2359) [bcx.class:?]
    at net.minecraft.client.network.NetHandlerPlayClient.func_147282_a(NetHandlerPlayClient.java:276) [bll.class:?]
    at net.minecraft.network.play.server.SPacketJoinGame.func_148833_a(SourceFile:76) [gw.class:?]
    at net.minecraft.network.play.server.SPacketJoinGame.func_148833_a(SourceFile:13) [gw.class:?]
    at net.minecraft.network.PacketThreadUtil$1.run(SourceFile:13) [fl$1.class:?]
    at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) [?:1.8.0_92]
    at java.util.concurrent.FutureTask.run(FutureTask.java:266) [?:1.8.0_92]
    at net.minecraft.util.Util.func_181617_a(SourceFile:45) [h.class:?]
    at net.minecraft.client.Minecraft.func_71411_J(Minecraft.java:1045) [bcx.class:?]
    at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:371) [bcx.class:?]
    at net.minecraft.client.main.Main.main(SourceFile:124) [Main.class:?]
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_92]
    at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_92]
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_92]
    at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_92]
    at net.minecraft.launchwrapper.Launch.launch(Launch.java:135) [launchwrapper-1.12.jar:?]
    at net.minecraft.launchwrapper.Launch.main(Launch.java:28) [launchwrapper-1.12.jar:?]`

**Comment by drakray** [comment]
and this when I tried to reconnect

`java.io.IOException: Une connexion existante a d󠪴re fermꥠpar lӨ��distant at sun.nio.ch.SocketDispatcher.read0(Native Method) ~[?:1.8.0_92] at sun.nio.ch.SocketDispatcher.read(SocketDispatcher.java:43) ~[?:1.8.0_92] at sun.nio.ch.IOUtil.readIntoNativeBuffer(IOUtil.java:223) ~[?:1.8.0_92] at sun.nio.ch.IOUtil.read(IOUtil.java:192) ~[?:1.8.0_92] at sun.nio.ch.SocketChannelImpl.read(SocketChannelImpl.java:380) ~[?:1.8.0_92] at io.netty.buffer.UnpooledUnsafeDirectByteBuf.setBytes(UnpooledUnsafeDirectByteBuf.java:446) ~[UnpooledUnsafeDirectByteBuf.class:4.0.23.Final] at io.netty.buffer.AbstractByteBuf.writeBytes(AbstractByteBuf.java:881) ~[AbstractByteBuf.class:4.0.23.Final] at io.netty.channel.socket.nio.NioSocketChannel.doReadBytes(NioSocketChannel.java:225) ~[NioSocketChannel.class:4.0.23.Final] at io.netty.channel.nio.AbstractNioByteChannel$NioByteUnsafe.read(AbstractNioByteChannel.java:119) [AbstractNioByteChannel$NioByteUnsafe.class:4.0.23.Final] at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:511) [NioEventLoop.class:4.0.23.Final] at io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:468) [NioEventLoop.class:4.0.23.Final] at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:382) [NioEventLoop.class:4.0.23.Final] at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:354) [NioEventLoop.class:4.0.23.Final] at io.netty.util.concurrent.SingleThreadEventExecutor$2.run(SingleThreadEventExecutor.java:116) [SingleThreadEventExecutor$2.class:4.0.23.Final] at java.lang.Thread.run(Thread.java:745) [?:1.8.0_92]`

**Comment by drakray** [comment]
Connecting with another account work
Destroying Uranium in creative don't crash
Droping Uranium Ore on the ground is fine too

I used MoreItems's Obsidian Pickaxe, with Unbreaking, Fortune, Efficiency and Mending, which also crashed my other player
Trying to mine Uranium with another non-enchanted pickaxe does not work, the Uranium respawn

EDIT: deleting the player file fix the problem(by losing everything, but still)

When I go back to the place I broke the U, where it seems to have dissapeared, they are still there

**Comment by Drakray** [comment]
I used MoreItems's Obsidian Pickaxe, with Unbreaking, Fortune, Efficiency and Mending, which also crashed my other player
Trying to mine Uranium with another non-enchanted pickaxe does not work, the Uranium respawn

**Comment by drakray** [comment]
The bug is caused when breaking a Uranium Ore with a pickaxe(diamond) enchanted with Efficiency 5. The block seems to be absent, but is only invisible. right-clicking on the block make it reappear. Walking ON the invisible block make the crash.

**Comment by drakray** [comment]
going in creative with a non-crashed account and "cleaning" the Ore block make the crashed account able to connect
