### ISSUE TITLE
[1.10.2-3.4.4.13] Game crashed when shooting a slime with the advanced ray gun

### ISSUE THREAD

**Issue by Lothrazar** [grim3212/grim-pack#17]
I was in creative mode on superflat if that matters

---- Minecraft Crash Report ----

WARNING: coremods are present:
  BetterFoliageLoader (BetterFoliage-MC1.10-2.1.0.jar)
  LoadingPlugin (Quark-r1.0-51.jar)
  AppleCore (AppleCore-mc1.10.2-2.0.0.jar)
  LoadingPlugin (ChunkAnimator-MC1.9.4-1.2.jar)
  FMLPlugin (InventoryTweaks-1.61-58.jar)
  MalisisCorePlugin (malisiscore-1.9.4-4.1.1.jar)
  dsurroundcore_unofficial (DynamicSurroundingsUnofficial-1.10.2-3.0.6.1BETA.jar)
Contact their authors BEFORE contacting forge

// There are four lights!

Time: 8/16/16 10:26 PM
Description: Ticking entity

java.lang.NullPointerException: Ticking entity
    at net.minecraft.network.datasync.EntityDataManager.func_187225_a(SourceFile:116)
    at net.minecraft.entity.projectile.EntityArrow.func_70241_g(SourceFile:555)
    at org.blockartistry.mod.DynSurround.client.DamageEffectHandler.onLivingHurt(DamageEffectHandler.java:119)
    at net.minecraftforge.fml.common.eventhandler.ASMEventHandler_290_DamageEffectHandler_onLivingHurt_LivingHurtEvent.invoke(.dynamic)
    at net.minecraftforge.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:72)
    at net.minecraftforge.fml.common.eventhandler.EventBus.post(EventBus.java:168)
    at net.minecraftforge.common.ForgeHooks.onLivingHurt(ForgeHooks.java:502)
    at net.minecraft.entity.EntityLivingBase.func_70665_d(EntityLivingBase.java:1296)
    at net.minecraft.entity.EntityLivingBase.func_70097_a(EntityLivingBase.java:890)
    at com.grim3212.mc.pack.core.entity.EntityProjectile.func_184549_a(EntityProjectile.java:336)
    at com.grim3212.mc.pack.core.entity.EntityProjectile.func_70071_h_(EntityProjectile.java:261)
    at com.grim3212.mc.pack.tools.entity.EntityRayw.func_70071_h_(EntityRayw.java:41)
    at net.minecraft.world.World.func_72866_a(World.java:1962)
    at net.minecraft.world.WorldServer.func_72866_a(WorldServer.java:837)
    at net.minecraft.world.World.func_72870_g(World.java:1932)
    at net.minecraft.world.World.func_72939_s(World.java:1748)
    at net.minecraft.world.WorldServer.func_72939_s(WorldServer.java:618)
    at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:709)
    at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:613)
    at net.minecraft.server.integrated.IntegratedServer.func_71217_p(IntegratedServer.java:240)
    at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:471)
    at java.lang.Thread.run(Thread.java:745)
## A detailed walkthrough of the error, its code path and all known details is as follows:

-- Head --
Thread: Server thread
Stacktrace:
    at net.minecraft.network.datasync.EntityDataManager.func_187225_a(SourceFile:116)
    at net.minecraft.entity.projectile.EntityArrow.func_70241_g(SourceFile:555)
    at org.blockartistry.mod.DynSurround.client.DamageEffectHandler.onLivingHurt(DamageEffectHandler.java:119)
    at net.minecraftforge.fml.common.eventhandler.ASMEventHandler_290_DamageEffectHandler_onLivingHurt_LivingHurtEvent.invoke(.dynamic)
    at net.minecraftforge.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:72)
    at net.minecraftforge.fml.common.eventhandler.EventBus.post(EventBus.java:168)
    at net.minecraftforge.common.ForgeHooks.onLivingHurt(ForgeHooks.java:502)
    at net.minecraft.entity.EntityLivingBase.func_70665_d(EntityLivingBase.java:1296)
    at net.minecraft.entity.EntityLivingBase.func_70097_a(EntityLivingBase.java:890)
    at com.grim3212.mc.pack.core.entity.EntityProjectile.func_184549_a(EntityProjectile.java:336)
    at com.grim3212.mc.pack.core.entity.EntityProjectile.func_70071_h_(EntityProjectile.java:261)
    at com.grim3212.mc.pack.tools.entity.EntityRayw.func_70071_h_(EntityRayw.java:41)
    at net.minecraft.world.World.func_72866_a(World.java:1962)
    at net.minecraft.world.WorldServer.func_72866_a(WorldServer.java:837)
    at net.minecraft.world.World.func_72870_g(World.java:1932)

-- Entity being ticked --
Details:
    Entity Type: grimpack.AdvRayShot (com.grim3212.mc.pack.tools.entity.EntityAdvRayw)
    Entity ID: 197213
    Entity Name: entity.grimpack.AdvRayShot.name
    Entity's Exact location: -568.59, 6.20, 207.77
    Entity's Block location: World: (-569,6,207), Chunk: (at 7,0,15 in -36,12; contains blocks -576,0,192 to -561,255,207), Region: (-2,0; contains chunks -64,0 to -33,31, blocks -1024,0,0 to -513,255,511)
    Entity's Momentum: 0.51, 0.02, 2.31
    Entity's Passengers: []
    Entity's Vehicle: ~~ERROR~~ NullPointerException: null
Stacktrace:
    at net.minecraft.world.World.func_72939_s(World.java:1748)
    at net.minecraft.world.WorldServer.func_72939_s(WorldServer.java:618)

-- Affected level --
Details:
    Level name: TESTING
    All players: 1 total; [EntityPlayerMP['Lothrazar'/26, l='TESTING', x=-582.13, y=4.00, z=146.55]]
    Chunk stats: ServerChunkCache: 438 Drop: 0
    Level seed: -7335415141906106677
    Level generator: ID 01 - flat, ver 0. Features enabled: true
    Level generator options: 
    Level spawn location: World: (-581,4,139), Chunk: (at 11,0,11 in -37,8; contains blocks -592,0,128 to -577,255,143), Region: (-2,0; contains chunks -64,0 to -33,31, blocks -1024,0,0 to -513,255,511)
    Level time: 1013 game time, 0 day time
    Level dimension: 0
    Level storage version: 0x04ABD - Anvil
    Level weather: Rain time: 55676 (now: false), thunder time: 92754 (now: false)
    Level game mode: Game mode: creative (ID 1). Hardcore: false. Cheats: true
Stacktrace:
    at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:709)
    at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:613)
    at net.minecraft.server.integrated.IntegratedServer.func_71217_p(IntegratedServer.java:240)
    at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:471)
    at java.lang.Thread.run(Thread.java:745)

-- System Details --
Details:
    Minecraft Version: 1.10.2
    Operating System: Windows 10 (amd64) version 10.0
    Java Version: 1.8.0_25, Oracle Corporation
    Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
    Memory: 461169872 bytes (439 MB) / 1060372480 bytes (1011 MB) up to 1060372480 bytes (1011 MB)
    JVM Flags: 6 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xmx1G -XX:+UseConcMarkSweepGC -XX:+CMSIncrementalMode -XX:-UseAdaptiveSizePolicy -Xmn128M
    IntCache: cache: 0, tcache: 0, allocated: 0, tallocated: 0
    FML: MCP 9.32 Powered by Forge 12.18.1.2061 Optifine OptiFine_1.10.2_HD_U_C2 60 mods loaded, 60 mods active
    States: 'U' = Unloaded 'L' = Loaded 'C' = Constructed 'H' = Pre-initialized 'I' = Initialized 'J' = Post-initialized 'A' = Available 'D' = Disabled 'E' = Errored
    UCHIJAAAA   mcp{9.19} [Minecraft Coder Pack](minecraft.jar) 
    UCHIJAAAA   FML{8.0.99.99} [Forge Mod Loader](forge-1.10.2-12.18.1.2061.jar) 
    UCHIJAAAA   Forge{12.18.1.2061} [Minecraft Forge](forge-1.10.2-12.18.1.2061.jar) 
    UCHIJAAAA   lazAnvils{1.2.1.3} [Anvil Enchantments](anvils-1.10.2-1.2.1.3.jar) 
    UCHIJAAAA   JEI{3.8.1.243} [Just Enough Items](jei_1.10.2-3.8.1.243.jar) 
    UCHIJAAAA   AppleCore{2.0.0} [AppleCore](AppleCore-mc1.10.2-2.0.0.jar) 
    UCHIJAAAA   appleskin{1.0.1} [AppleSkin](AppleSkin-mc1.10.2-1.0.1.jar) 
    UCHIJAAAA   arrowcammod{2.2.0} [Arrow Cam Mod](ArrowCamMod-1.10.2-2.2.0.jar) 
    UCHIJAAAA   betterbuilderswands{0.6.5} [Better Builder's Wands](BetterBuildersWands-0.6.5-1.10r138+8595fc7.jar) 
    UCHIJAAAA   bettercombatmod{1.3.0} [Better Combat](BetterCombat-1.3.jar) 
    UCHIJAAAA   BetterFoliage{2.1.0} [Better Foliage](BetterFoliage-MC1.10-2.1.0.jar) 
    UCHIJAAAA   Chameleon{1.10-2.1.7} [Chameleon](Chameleon-1.10-2.1.7.jar) 
    UCHIJAAAA   ChunkAnimator{1.2} [Chunk Animator](ChunkAnimator-MC1.9.4-1.2.jar) 
    UCHIJAAAA   combathelp{1.0.3} [Combat Help](combathelp-1.9.4-1.0.3.jar) 
    UCHIJAAAA   MineTweaker3{3.0.10} [MineTweaker 3](CraftTweaker-1.10.2-3.0.10.jar) 
    UCHIJAAAA   cs{1.0.2} [Configurable Villager to Door Ratio](cs-1.0.2.jar) 
    UCHIJAAAA   wonderfulwands{2.2.0} [Wonderful Wands](CyanosWonderfulWands_1.10.2-2.2.0.jar) 
    UCHIJAAAA   cyclicmagic{1.5.2} [Cyclic](Cyclic-1.10.2-1.5.2.jar) 
    UCHIJAAAA   Ding{MC1.9.0v2} [Ding](Ding-1.10.2-1.0.0.jar) 
    UCHIJAAAA   disenchanter{1.4} [Disenchanter](disenchanter-[1.9.4]1.4.jar) 
    UCHIJAAAA   lootablebodies{2.2.0} [DrCyano's Lootable Bodies](DrCyanosLootableBodies_1.10.2-2.2.0.jar) 
    UCHIJAAAA   dsurroundunofficial{3.0.6.1BETA} [Dynamic Surroundings Unofficial](DynamicSurroundingsUnofficial-1.10.2-3.0.6.1BETA.jar) 
    UCHIJAAAA   EnderZoo{1.10-1.2.3.43} [Ender Zoo](EnderZoo-1.10-1.2.3.43.jar) 
    UCHIJAAAA   FastLeaveDecay{1.1} [Fast Leave Decay](FastLeaveDecay-MC1.10-1.2.1.jar) 
    UCHIJAAAA   forgecreeperheal{1.3.0} [Forge Creeper Heal](forgecreeperheal-1.10.2-1.3.0.jar) 
    UCHIJAAAA   GlobalGameRules{1.0} [Global GameRules](GlobalGameRules-1.10.2-1.0.jar) 
    UCHIJAAAA   grapple_hooks{1.0.8} [Grapple Hooks](Grapple-Hooks-1.10.2-1.0.8.jar) 
    UCHIJAAAA   grimpack{3.4.4.13} [Grim Pack](Grim Pack-1.10.2-3.4.4.13.jar) 
    UCHIJAAAA   HoloInventory{2.0.1.135} [HoloInventory](HoloInventory-1.9.4-2.0.1.135.jar) 
    UCHIJAAAA   InfernalMobs{1.7.1} [Infernal Mobs](InfernalMobs-1.10.jar) 
    UCHIJAAAA   inventorytweaks{1.61-58-a1fd884} [Inventory Tweaks](InventoryTweaks-1.61-58.jar) 
    UCHIJAAAA   journeymap{1.10.2-5.2.4} [JourneyMap](journeymap-1.10.2-5.2.4-unlimited.jar) 
    UCHIJAAAA   jeresources{0.4.9.50} [Just Enough Resources](JustEnoughResources-1.10.2-0.4.9.50.jar) 
    UCHIJAAAA   kleeslabs{3.3.1} [KleeSlabs](KleeSlabs-mc1.10-3.3.1.jar) 
    UCHIJAAAA   LunatriusCore{1.1.2.36} [LunatriusCore](LunatriusCore-1.10.2-1.1.2.36-universal.jar) 
    UCHIJAAAA   LaserLevel{2.1.0.13} [Laser Level](LaserLevel-1.10.2-2.1.0.13-universal.jar) 
    UCHIJAAAA   lteleporters{1.1.3} [Lemon's Simple Teleporters](LemonsTeleporters-1.1.3.jar) 
    UCHIJAAAA   malisiscore{1.9.4-4.1.1} [MalisisCore](malisiscore-1.9.4-4.1.1.jar) 
    UCHIJAAAA   malisisdoors{1.9.4-5.0.3} [MalisisDoors](malisisdoors-1.9.4-5.0.3.jar) 
    UCHIJAAAA   mineTunes{1.2-9} [mineTunes](MineTunes 1.2-9.jar) 
    UCHIJAAAA   ModLister{1.10-2.1.6} [ModLister](ModLister-1.10-2.1.6.jar) 
    UCHIJAAAA   powerinventory{2.2.2} [Overpowered Inventory](OverpoweredInventory-1.10.2-2.2.2.jar) 
    UCHIJAAAA   PersistentBits{1.0.3} [Persistent Bits](PersistentBits-1.10.2-1.0.3.jar) 
    UCHIJAAAA   progressiveautomation{1.6.49} [Progressive Automation](ProgressiveAutomation-1.10.2-1.6.49.jar) 
    UCHIJAAAA   ProjectE{1.9.4-PE1.0.5B} [ProjectE](ProjectE-1.9.4-PE1.0.5B.jar) 
    UCHIJAAAA   Quark{r1.0-51} [Quark](Quark-r1.0-51.jar) 
    UCHIJAAAA   recallstones{0.6.3} [Recall Stones](RecallStones-1.10.2-0.6.3.jar) 
    UCHIJAAAA   xreliquary{1.10.2-1.3.3.467} [Reliquary](Reliquary-1.10.2-1.3.3.467.jar) 
    UCHIJAAAA   roots{0.111} [Roots](roots-1.10.2-0.111.0.jar) 
    UCHIJAAAA   Schematica{1.7.8.151} [Schematica](Schematica-1.10.2-1.7.8.151-universal.jar) 
    UCHIJAAAA   SimilsaxTranstructors{1.10.2.18} [Similsax Transtructors](SimilsaxTranstructors-1.10.2.18.jar) 
    UCHIJAAAA   SophisticatedWolves{3.6.1} [SophisticatedWolves](SophisticatedWolves-3.6.3.jar) 
    UCHIJAAAA   soundfilters{0.9_for_1.9} [Sound Filters](SoundFilters-0.9_for_1.10.jar) 
    UCHIJAAAA   Stackie{1.6.0.44} [Stackie](Stackie-1.10.2-1.6.0.44-universal.jar) 
    UCHIJAAAA   StorageDrawers{1.10.2-3.2.4} [Storage Drawers](StorageDrawers-1.10.2-3.2.4.jar) 
    UCHIJAAAA   supercraftingframe{1.2.0.85} [Super Crafting Frame](supercraftingframe-1.10.2-1.2.0.85.jar) 
    UCHIJAAAA   VeinMiner{0.34.1_1.9-73be663} [Vein Miner](VeinMiner-0.34.1-1.9r571+73be663.jar) 
    UCHIJAAAA   VeinMinerModSupport{0.34.1_1.9-73be663} [Mod Support](VeinMiner-0.34.1-1.9r571+73be663.jar) 
    UCHIJAAAA   vc{v0.2.9b-mc1.10.2} [ViesCraft](ViesCraft-0.2.9b-mc1.10.2.jar) 
    UCHIJAAAA   villagebox{0.5.0} [Village Box](villagebox-1.10.2-0.5.0.jar) 
    Loaded coremods (and transformers): 
BetterFoliageLoader (BetterFoliage-MC1.10-2.1.0.jar)
  mods.betterfoliage.loader.BetterFoliageTransformer
LoadingPlugin (Quark-r1.0-51.jar)
  vazkii.quark.base.asm.ClassTransformer
AppleCore (AppleCore-mc1.10.2-2.0.0.jar)
  squeek.applecore.asm.TransformerModuleHandler
LoadingPlugin (ChunkAnimator-MC1.9.4-1.2.jar)
  lumien.chunkanimator.asm.ClassTransformer
FMLPlugin (InventoryTweaks-1.61-58.jar)
  invtweaks.forge.asm.ContainerTransformer
MalisisCorePlugin (malisiscore-1.9.4-4.1.1.jar)
  net.malisis.core.util.chunkcollision.ChunkCollisionTransformer
  net.malisis.core.util.chunkblock.ChunkBlockTransformer
  net.malisis.core.renderer.transformer.MalisisRendererTransformer
  net.malisis.core.renderer.icon.asm.TextureMapTransformer
  net.malisis.core.util.clientnotif.ClientNotifTransformer
dsurroundcore_unofficial (DynamicSurroundingsUnofficial-1.10.2-3.0.6.1BETA.jar)
  org.blockartistry.mod.DynSurround.asm.Transformer
    GL info: ~~ERROR~~ RuntimeException: No OpenGL context found in the current thread.
    Profiler Position: N/A (disabled)
    Player Count: 1 / 8; [EntityPlayerMP['Lothrazar'/26, l='TESTING', x=-582.13, y=4.00, z=146.55]]
    Type: Integrated Server (map_client.txt)
    Is Modded: Definitely; Client brand changed to 'fml,forge'
    OptiFine Version: OptiFine_1.10.2_HD_U_C2
    Render Distance Chunks: 8
    Mipmaps: 4
    Anisotropic Filtering: 1
    Antialiasing: 0
    Multitexture: false
    Shaders: null
    OpenGlVersion: 3.3.0
    OpenGlRenderer: GeForce 9500 GS/PCIe/SSE2
    OpenGlVendor: NVIDIA Corporation
    CpuCount: 4

**Comment by Lothrazar** [comment]
Nevermind, actually looking at the logs, DynamicSurroundings has an error before your mod does.

Sure enough, once I remove the mod file "DynamicSurroundingsUnofficial-1.10.2-3.0.6.1BETA" , the raygun no longer crashes the game!

So i cross- reported it to their devvs as wel

https://minecraft.curseforge.com/projects/dynamic-surroundings-unofficial/issues/4

**Comment by grim3212** [comment]
Well I agree that it also looks like it is on their end. So I'll close this for right now unless it turns out its on my end.

**Comment by grim3212** [comment]
This may have actually been fixed with 3f2f03c
